#!/bin/sh

echo "Running PHP-CS-Fixer..."
php ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php index.php

echo "Running PHPStan..."
php ./vendor/bin/phpstan analyze --memory-limit=512M index.php

if [ $? -ne 0 ]; then
    echo "PHPStan found issues. Please fix them before committing."
    exit 1
fi

echo "All checks passed!"
